# Generated by Django 3.2.6 on 2021-09-14 09:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anlytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_name', models.CharField(max_length=25)),
                ('analytics_data', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_DOB', models.DateField(auto_now_add=True)),
                ('candidate_registration_date', models.DateField(default=datetime.date.today)),
                ('Candidates_gender', models.CharField(max_length=10)),
                ('candidate_type', models.CharField(default='will be choices personal/party', max_length=255)),
                ('education_level', models.CharField(choices=[('10', '10 or Below'), ('DIPLOMA', 'Diploma'), ('BD', "Bachelor's Degree"), ('MD', "Master's Degree"), ('Phd', 'Phd'), ('Prf.', 'Professor')], max_length=25)),
                ('participation_region', models.CharField(max_length=255)),
                ('candidate_status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Types_of_observers', models.CharField(default='DOMESTIC, INTERNATIONA, MEDIA, POLITICAL PARTY AGENT, CANDIDATE AGENT', max_length=25)),
                ('observer_name', models.CharField(max_length=50)),
                ('observer_regisration_date', models.DateField(default=datetime.date.today)),
                ('observer_organization', models.CharField(max_length=25)),
                ('observer_type', models.CharField(default='will be choices from types of choices', max_length=255)),
                ('observer_status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('party_registration_date', models.DateField(default=datetime.date.today)),
                ('part_logo', models.ImageField(upload_to='files')),
                ('party_type', models.CharField(choices=[('F', 'Federal'), ('R', 'Regional')], max_length=255)),
                ('participation_regions', models.CharField(max_length=255)),
                ('party_status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Referendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referendum_name', models.CharField(max_length=255)),
                ('referendum_registration_date', models.DateField(default=datetime.date.today)),
                ('referendum_date', models.DurationField(default='P4DT1H15M20S')),
                ('referendum_regions', models.CharField(max_length=25)),
                ('referendum_stations', models.CharField(default='will be foreign key to referendum stations', max_length=255)),
                ('referendum_observers', models.CharField(default='ggg', max_length=25)),
                ('referendum_analytics', models.CharField(max_length=25)),
                ('referendum_result', models.CharField(max_length=25)),
                ('referendum_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=25)),
                ('region_id', models.CharField(max_length=25)),
                ('polling_stations', models.CharField(default='foreign key to polling stations', max_length=255)),
                ('location', models.CharField(default='will be changed to point datafield', max_length=255)),
                ('region_status', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ReferendumOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referendum_option_name', models.CharField(max_length=25)),
                ('referendum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.referendum')),
            ],
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_station_id', models.CharField(max_length=25)),
                ('polling_station_name', models.CharField(max_length=25)),
                ('list_of_candidates', models.CharField(default='foreign key to candidates', max_length=255)),
                ('polling_station_status', models.CharField(max_length=25)),
                ('found_in_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.regions')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=255)),
                ('election_registration_date', models.DateField(default=datetime.date.today)),
                ('election_year', models.DateField()),
                ('election_type', models.CharField(default='will be regional or federal', max_length=255)),
                ('election_date', models.DateField(default='2021-08-23')),
                ('election_result', models.CharField(max_length=255)),
                ('political_parties', models.CharField(max_length=255)),
                ('election_regions', models.CharField(max_length=255)),
                ('polling_stations', models.CharField(max_length=255)),
                ('observers', models.CharField(max_length=255)),
                ('analytics', models.CharField(max_length=255)),
                ('elelction_status', models.CharField(max_length=25)),
                ('candidates', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.candidates')),
            ],
        ),
        migrations.AddField(
            model_name='candidates',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.party'),
        ),
    ]
