# Generated by Django 3.2.6 on 2021-09-26 16:10

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_DOB', models.DateField(default='1987-03-24')),
                ('candidate_registration_date', models.DateField(default=datetime.date.today)),
                ('Candidates_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('candidate_type', models.CharField(choices=[('Party', 'Party'), ('Personal', 'Personal')], default='Party', max_length=255)),
                ('education_level', models.CharField(choices=[('10', '10 or Below'), ('DIPLOMA', 'Diploma'), ('BD', "Bachelor's Degree"), ('MD', "Master's Degree"), ('Phd', 'Phd'), ('Prf.', 'Professor')], max_length=25)),
                ('participates_for', models.CharField(choices=[("For House of Peoples' Representatives", "For House of Peoples' Representatives"), ('For Regional Government Council', 'For Regional Government Council')], default='For Regional Government Council', max_length=50)),
                ('candidate_photo', models.ImageField(upload_to='candidates_image/')),
                ('candidate_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=25)),
                ('number_of_votes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=255)),
                ('election_registration_date', models.DateField(default=datetime.date.today)),
                ('election_year', models.DateField()),
                ('election_type', models.CharField(choices=[('General', 'General'), ('Regional', 'Regional'), ('Local', 'Local'), ('Federal', 'Federal')], default='General', max_length=255)),
                ('election_date', models.DateField(default='2021-08-23')),
                ('election_result', models.CharField(default='Election Result 1', max_length=255)),
                ('elelction_status', models.CharField(default='Active', max_length=25, verbose_name=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')])),
            ],
        ),
        migrations.CreateModel(
            name='ElectionRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_region_id', models.CharField(max_length=25)),
                ('election_region_name', models.CharField(max_length=25)),
                ('seats_for_HPR', models.PositiveIntegerField()),
                ('seats_for_RGC', models.PositiveIntegerField()),
                ('election_region_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_station_id', models.CharField(max_length=25)),
                ('polling_station_name', models.CharField(max_length=50)),
                ('polling_station_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=25)),
                ('number_of_voters', models.PositiveIntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.election')),
                ('found_in_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.electionregions')),
            ],
        ),
        migrations.CreateModel(
            name='Referendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referendum_name', models.CharField(max_length=255)),
                ('referendum_registration_date', models.DateField(default=datetime.date.today)),
                ('referendum_date', models.DateField(default='2021-10-15')),
                ('referendum_result', models.CharField(default='Referendum Result 1', max_length=25)),
                ('referendum_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=255)),
                ('referendum_regions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.electionregions')),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.CharField(max_length=25)),
                ('region_name', models.CharField(max_length=50)),
                ('seats_for_HPR', models.PositiveIntegerField()),
                ('seats_for_RGC', models.PositiveIntegerField()),
                ('region_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Names contain non alphabetic character(s), only alphabets are allowed')])),
                ('middle_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Names contain non alphabetic character(s), only alphabets are allowed')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Names contain non alphabetic character(s), only alphabets are allowed')])),
                ('voter_password', models.CharField(max_length=25)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('citizen_registration_number', models.PositiveIntegerField()),
                ('voter_registratio_id', models.CharField(max_length=255)),
                ('woreda', models.IntegerField()),
                ('sub_city', models.CharField(max_length=25)),
                ('house_number', models.IntegerField()),
                ('voted_time', models.DateTimeField(blank=True, null=True)),
                ('at_polling_station', models.BooleanField(default=True, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('disability_type', models.CharField(choices=[('Vision Impairmnet', 'Vision Impairmnet'), ('Deaf or Hard of Hearing', 'Deaf or Hard of Hearing'), ('Physical Disability', 'Physical Disability')], default=None, max_length=50)),
                ('voter_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=25)),
                ('duration_of_living_in_the_current_election_region', models.CharField(choices=[('6 Months', '6 Months'), ('7 Months - 1 Year', '7 Months - 1 Year'), ('Two Years', 'Two Years'), ('2 - 5 Years', '2 - 5 Years'), ('5 - 10 Years', '5 - 10 Years'), ('10 - 15 Years', '10 - 15 Years'), ('15 - 20 Years', '15 - 20 Years'), ('More Than 20 Years', 'More Than 20 Years')], default='6 Months', max_length=50)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='election.election')),
                ('referendum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='election.referendum')),
                ('registerd_at', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.pollingstation')),
                ('voted_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voted_place', to='election.pollingstation')),
                ('voted_to', models.ManyToManyField(blank=True, to='election.Candidates')),
            ],
        ),
        migrations.CreateModel(
            name='ReferendumOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referendum_option_name', models.CharField(max_length=25)),
                ('number_of_votes', models.PositiveIntegerField(default=0)),
                ('referendum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.referendum')),
            ],
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='referendum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.referendum'),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('party_registration_date', models.DateField(default=datetime.date.today)),
                ('party_logo', models.ImageField(upload_to='files')),
                ('party_type', models.CharField(choices=[('Federal', 'Federal'), ('Regional', 'Regional')], default='Federal', max_length=255)),
                ('party_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=25)),
                ('number_of_votes', models.PositiveBigIntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.election')),
                ('participation_regions', models.ManyToManyField(to='election.ElectionRegions')),
            ],
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer_name', models.CharField(max_length=50)),
                ('observer_regisration_date', models.DateField(default=datetime.date.today)),
                ('observer_organization', models.CharField(max_length=25)),
                ('observer_type', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International'), ('Media', 'Media'), ('Political Party Agent', 'Political Party Agent'), ('Candidate Agent', 'Candidate Agent')], default='Political Party Agent', max_length=255)),
                ('observer_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=25)),
                ('election', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='election.election')),
                ('referendum', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='election.referendum')),
            ],
        ),
        migrations.AddField(
            model_name='electionregions',
            name='regions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.regions'),
        ),
        migrations.AddField(
            model_name='election',
            name='election_regions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.electionregions'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.election'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='participation_region',
            field=models.ManyToManyField(to='election.ElectionRegions'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='election.party'),
        ),
        migrations.CreateModel(
            name='Anlytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytics_name', models.CharField(max_length=25)),
                ('analytics_data', models.CharField(max_length=255)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.election')),
                ('referendum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.referendum')),
            ],
        ),
    ]
