# Generated by Django 3.2.6 on 2021-09-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='candidates',
        ),
        migrations.AddField(
            model_name='canidates',
            name='candidates',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='election.party'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='part_logo',
            field=models.ImageField(upload_to='BASE DIR/files'),
        ),
    ]
