# Generated by Django 3.2.6 on 2021-09-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='participation_regions',
        ),
        migrations.AddField(
            model_name='party',
            name='participation_regions',
            field=models.ManyToManyField(to='election.Regions'),
        ),
    ]
