# Generated by Django 3.2.6 on 2021-09-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20210918_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regions',
            name='location',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='polling_stations',
        ),
        migrations.RemoveField(
            model_name='regions',
            name='region_status',
        ),
        migrations.AddField(
            model_name='regions',
            name='Number_of_seats',
            field=models.PositiveIntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regions',
            name='region_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voted_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voted_place', to='election.pollingstation'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voted_to',
            field=models.ManyToManyField(blank=True, to='election.Candidates'),
        ),
        migrations.CreateModel(
            name='ElectionRegions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_region_name', models.CharField(max_length=25)),
                ('election_region_id', models.CharField(max_length=25)),
                ('location', models.CharField(default='will be changed to point datafield', max_length=255)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('election_region_status', models.CharField(max_length=25)),
                ('regions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.regions')),
            ],
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='found_in_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.electionregions'),
        ),
    ]
