# Generated by Django 3.2.6 on 2021-09-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20210909_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canidates',
            old_name='candidates',
            new_name='party',
        ),
    ]
