# Generated by Django 3.2.6 on 2021-09-21 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20210921_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingstation',
            name='found_in_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.regions'),
        ),
    ]
