# Generated by Django 3.2.6 on 2021-09-09 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_rename_candidates_canidates_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='election_date',
        ),
        migrations.AlterField(
            model_name='election',
            name='candidates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.canidates'),
        ),
        migrations.AlterField(
            model_name='party',
            name='part_logo',
            field=models.ImageField(upload_to='files'),
        ),
    ]
