# Generated by Django 3.2.6 on 2021-09-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20210927_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='voter_registratio_id',
            new_name='voter_registration_id',
        ),
    ]
