# Generated by Django 3.2.6 on 2021-09-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_rename_voter_registratio_id_voter_voter_registration_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsToBEApproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=25)),
                ('entity_id', models.PositiveIntegerField()),
                ('entity', models.JSONField()),
            ],
        ),
    ]
