# Generated by Django 3.2.6 on 2021-09-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_auto_20210909_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_date',
            field=models.DateField(default='2021-08-23'),
        ),
    ]
