# Generated by Django 3.2.6 on 2021-09-09 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0001_initial'),
        ('election', '0005_election_election_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Canidates',
            new_name='Candidates',
        ),
        migrations.RenameField(
            model_name='election',
            old_name='elelction_year',
            new_name='election_year',
        ),
        migrations.AddField(
            model_name='party',
            name='candidate_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='election.party'),
        ),
    ]
