# Generated by Django 3.2.6 on 2021-09-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_auto_20210921_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='participation_region',
            field=models.ManyToManyField(to='election.ElectionRegions'),
        ),
    ]
