# Generated by Django 3.2.6 on 2021-09-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_actionstobeapproved_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionstobeapproved',
            name='data',
        ),
        migrations.AddField(
            model_name='actionstobeapproved',
            name='action_type',
            field=models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], default='Create', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionstobeapproved',
            name='data_type',
            field=models.CharField(default='Regions', max_length=50),
            preserve_default=False,
        ),
    ]
