# Generated by Django 3.2.6 on 2021-09-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_alter_candidates_participation_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='region_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=25),
        ),
        migrations.AlterField(
            model_name='electionregions',
            name='election_region_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=25),
        ),
    ]
