# Generated by Django 3.2.6 on 2021-09-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_remove_electionregions_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionregions',
            old_name='number_of_seats',
            new_name='seats_for_HPR',
        ),
        migrations.AddField(
            model_name='electionregions',
            name='seats_for_RGC',
            field=models.PositiveIntegerField(default=23),
            preserve_default=False,
        ),
    ]
