# Generated by Django 3.2.6 on 2021-09-10 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_referendum_referendum_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referendum',
            name='referendum_options',
        ),
        migrations.AddField(
            model_name='referendumoptions',
            name='referendum_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='election.referendum'),
            preserve_default=False,
        ),
    ]
