# Generated by Django 3.2.6 on 2021-09-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_auto_20210911_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referendumoptions',
            old_name='referendum_link',
            new_name='referendum',
        ),
    ]
