# Generated by Django 3.2.6 on 2021-09-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0010_auto_20210922_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regions',
            old_name='Number_of_seats',
            new_name='seats_for_HPR',
        ),
        migrations.AddField(
            model_name='regions',
            name='seats_for_RGC',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
