# Generated by Django 3.2.6 on 2021-09-22 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_auto_20210922_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observer',
            name='Types_of_observers',
        ),
        migrations.RemoveField(
            model_name='pollingstation',
            name='list_of_candidates',
        ),
        migrations.RemoveField(
            model_name='referendum',
            name='referendum_stations',
        ),
        migrations.AddField(
            model_name='candidates',
            name='Number_of_votes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referendum',
            name='referendum_election_regions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='election.electionregions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='duration_of_living_in_the_current_election_region',
            field=models.CharField(choices=[('6 Months', '6 Months'), ('7 Months - 1 Year', '7 Months - 1 Year'), ('Two Years', 'Two Years'), ('2 - 5 Years', '2 - 5 Years'), ('5 - 10 Years', '5 - 10 Years'), ('10 - 15 Years', '10 - 15 Years'), ('15 - 20 Years', '15 - 20 Years'), ('More Than 20 Years', 'More Than 20 Years')], default='6 Months', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='Candidates_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='candidate_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=25),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='candidate_type',
            field=models.CharField(choices=[('Party', 'Party'), ('Personal', 'Personal')], default='Party', max_length=255),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('General', 'General'), ('Regional', 'Regional'), ('Local', 'Local'), ('Federal', 'Federal')], default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='observer',
            name='observer_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=25),
        ),
        migrations.AlterField(
            model_name='observer',
            name='observer_type',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International'), ('Media', 'Media'), ('Political Party Agent', 'Political Party Agent'), ('Candidate Agent', 'Candidate Agent')], default='Political Party Agent', max_length=255),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='polling_station_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='polling_station_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=25),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='referendum_date',
            field=models.DateField(default='2021-10-15'),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='referendum_observers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.observer'),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='referendum_regions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.regions'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='disability_type',
            field=models.CharField(choices=[('Vision Impairmnet', 'Vision Impairmnet'), ('Deaf or Hard of Hearing', 'Deaf or Hard of Hearing'), ('Physical Disability', 'Physical Disability')], default=None, max_length=50),
        ),
    ]
