# Generated by Django 3.2.6 on 2021-09-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_rename_referendum_link_referendumoptions_referendum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingstation',
            name='found_in_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.regions'),
        ),
    ]
