# Generated by Django 3.2.6 on 2021-09-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0012_auto_20210922_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_password',
            field=models.CharField(default=12345, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='elelction_status',
            field=models.CharField(default='Active', max_length=25, verbose_name=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')]),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=25),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_type',
            field=models.CharField(choices=[('Federal', 'Federal'), ('Regional', 'Regional')], default='Federal', max_length=255),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='referendum_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], default='Active', max_length=255),
        ),
    ]
