# Generated by Django 3.2.6 on 2021-09-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0013_auto_20210922_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
