# Generated by Django 3.2.6 on 2021-09-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0014_alter_voter_voted_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='party',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='election.party'),
        ),
    ]
