# Generated by Django 3.2.6 on 2021-09-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0016_alter_candidates_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='Number_of_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
