# Generated by Django 3.2.6 on 2021-09-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0018_rename_number_of_votes_candidates_number_of_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='candidate_photo',
            field=models.ImageField(default='static\\dist\\img\x07vatar5.png', upload_to='candidates_image/'),
            preserve_default=False,
        ),
    ]
