# Generated by Django 3.2.6 on 2021-09-15 23:10

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvotingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Names contain non alphabetic character(s), only alphabets are allowed')])),
                ('middle_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Names contain non alphabetic character(s), only alphabets are allowed')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Names contain non alphabetic character(s), only alphabets are allowed')])),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('role', models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('NEBE Officer', 'NEBE Officer'), ('Voter Registrar', 'Voter Registrar'), ('PRR', 'Political Party Representative'), ('Observer', 'Observer')], default='Voter Registrar', max_length=50)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], max_length=15)),
                ('email', models.CharField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('active', models.BooleanField(default=True)),
                ('voter_registrar', models.BooleanField(default=False)),
                ('nebe_officer', models.BooleanField(default=False)),
                ('observer', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('Evoting_admin', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='files')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('evotinguser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systemuser.evotinguser')),
                ('employee_type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('systemuser.evotinguser',),
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('evotinguser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systemuser.evotinguser')),
                ('admin_id', models.CharField(max_length=25)),
                ('admin_status', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
            bases=('systemuser.evotinguser',),
        ),
    ]
