# Generated by Django 3.2.6 on 2021-09-14 09:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvotingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Names contain non alphabetic character(s), only alphabets are allowed')])),
                ('middle_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Names contain non alphabetic character(s), only alphabets are allowed')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Names contain non alphabetic character(s), only alphabets are allowed')])),
                ('registration_date', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('role', models.CharField(choices=[('SA', 'SuperAdmin'), ('NO', 'NEBE Officer'), ('VR', 'Voter Registrar'), ('PRR', 'Political Party Representative'), ('O', 'Observer'), ('V', 'Voter')], default='VR', max_length=50)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('B', 'Banned')], max_length=15)),
                ('email', models.CharField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('evotinguser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systemuser.evotinguser')),
                ('employee_type', models.CharField(max_length=255)),
                ('employee_photo', models.ImageField(upload_to='files')),
            ],
            options={
                'abstract': False,
            },
            bases=('systemuser.evotinguser',),
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('evotinguser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systemuser.evotinguser')),
                ('admin_id', models.CharField(max_length=25)),
                ('admin_status', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
            bases=('systemuser.evotinguser',),
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('evotinguser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='systemuser.evotinguser')),
                ('citizen_registration_number', models.PositiveIntegerField()),
                ('voter_registratio_id', models.CharField(max_length=255)),
                ('registerd_at', models.CharField(default='Addis Ababa', max_length=255)),
                ('woreda', models.IntegerField()),
                ('sub_city', models.CharField(max_length=25)),
                ('house_number', models.IntegerField()),
                ('voted_at', models.CharField(default='will be foreign key to polling stations', max_length=255)),
                ('voted_time', models.DateTimeField(auto_now_add=True)),
                ('at_polling_station', models.BooleanField(default=True)),
                ('disabled', models.BooleanField(default=False)),
                ('disability_type', models.CharField(choices=[('V', 'Vision Impairmnet'), ('D', 'Deaf or Hard of Hearing'), ('p', 'Physical Disability')], max_length=50)),
                ('duration_of_living_in_the_current_election_region', models.DurationField(default='P4DT1H15M20S')),
                ('voted_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.candidates')),
            ],
            options={
                'abstract': False,
            },
            bases=('systemuser.evotinguser',),
        ),
    ]
