# Generated by Django 3.2.6 on 2021-09-11 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0011_rename_referendum_link_referendumoptions_referendum'),
        ('systemuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='voted_to',
        ),
        migrations.AddField(
            model_name='voter',
            name='voted_to',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='election.candidates'),
            preserve_default=False,
        ),
    ]
