# Generated by Django 3.2.6 on 2021-09-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evotinguser',
            old_name='is_active',
            new_name='Evoting_admin',
        ),
        migrations.RenameField(
            model_name='evotinguser',
            old_name='is_admin',
            new_name='nebe_officer',
        ),
        migrations.RenameField(
            model_name='evotinguser',
            old_name='is_staff',
            new_name='observer',
        ),
        migrations.RenameField(
            model_name='evotinguser',
            old_name='is_superadmin',
            new_name='voter_registrar',
        ),
        migrations.AddField(
            model_name='evotinguser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evotinguser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='evotinguser',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evotinguser',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('NEBE Officer', 'NEBE Officer'), ('Voter Registrar', 'Voter Registrar'), ('PRR', 'Political Party Representative'), ('Observer', 'Observer'), ('Voter', 'Voter')], default='Voter Registrar', max_length=50),
        ),
        migrations.AlterField(
            model_name='evotinguser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], max_length=15),
        ),
    ]
