# Generated by Django 3.2.6 on 2021-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0002_auto_20210914_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='evotinguser',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
