# Generated by Django 3.2.6 on 2021-09-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0002_auto_20210911_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_photo',
            field=models.ImageField(default='files', upload_to='files'),
            preserve_default=False,
        ),
    ]
