# Generated by Django 3.2.6 on 2021-09-01 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0002_auto_20210901_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='voter_name',
            new_name='voter_father_name',
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_first_name',
            field=models.CharField(default='chala', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Names contain non alphabetic character(s), only alphabets are allowed')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_gfather_name',
            field=models.CharField(default='beyene', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Names contain non alphabetic character(s), only alphabets are allowed')]),
            preserve_default=False,
        ),
    ]
