# Generated by Django 3.2.6 on 2021-09-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0004_evotinguser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evotinguser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='evotinguser',
            name='is_superadmin',
        ),
    ]
