# Generated by Django 3.2.6 on 2021-09-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0005_auto_20210914_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='evotinguser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evotinguser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
