# Generated by Django 3.2.6 on 2021-09-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemuser', '0006_auto_20210914_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_photo',
        ),
        migrations.AddField(
            model_name='evotinguser',
            name='photo',
            field=models.ImageField(default='abc.jpeg', upload_to='files'),
            preserve_default=False,
        ),
    ]
